#' Run a linear model in Stan
#'
#' @param model_template model template generated by aug_model and updated by aug_assign_data
#' @param ... additional arguments passed to rstan::sampling
#'
#' @return Stanfit model output
#' @export
#'
#' @examples
#' aug_model("linear") |>
#'   aug_assign_data(X = Loblolly$age,
#'                    Y = Loblolly$height,
#'                    N = nrow(Loblolly)) |>
#'   aug_run()
aug_run <- function(model_template, ...) {

  # Detect model
  out <- switch(model_template$model,
         linear = rstan::sampling(stanmodels$linear, data = model_template, ...),
         constant_single = rstan::sampling(stanmodels$constant_single, data = model_template, ...))

  return(out)
}
